Update rubygem-hammer_cli_import to 0.11.3
Katello/katello-packaging pull request #287
Opened 2016-09-15 12:26 UTC by ehelms

2016-09-15 12:51 UTC, stbenjam requested changes
Please update the RPM spec to match the gemspec in terms of dependencies, that's why this happened to begin with.

If the deps were right, repoclosure would've failed when hammer_cli_katello was released and we'd have known sooner

2016-09-22 13:20 UTC, ehelms commented
@stbenjam updated the spec file

2016-09-22 13:37 UTC, stbenjam commented on rubygem-hammer_cli_import/rubygem-hammer_cli_import.spec
>  Requires: %{?scl_prefix}rubygem(hammer_cli) >= 0.1.3
There's no minimum in the gemspec

2016-09-22 13:37 UTC, stbenjam requested changes

2016-09-22 14:02 UTC, ehelms commented on rubygem-hammer_cli_import/rubygem-hammer_cli_import.spec
>  Requires: %{?scl_prefix}rubygem(hammer_cli) >= 0.1.3
Good call - updated

2016-09-22 14:12 UTC, stbenjam approved these changes

2016-09-22 14:12 UTC, stbenjam commented
ack!

2016-09-22 14:28 UTC, merged