Fixes #16586 - restart gofer with katello-service
Katello/katello-packaging pull request #291
Opened 2016-09-19 19:57 UTC by chris1984

2016-09-19 19:58 UTC, chris1984 commented
set to 30, so that it comes up last.

2016-09-20 14:01 UTC, daviddavis commented on katello/katello-service
> +  'goferd'		     => 30
nitpick: mind aligning the hash rocket here with the other lines?

2016-09-20 14:02 UTC, daviddavis requested changes
Looks good to me (aside from one small comment).

2016-09-20 14:30 UTC, chris1984 commented
@daviddavis thanks the review, corrections made with a new commit

2016-09-20 14:43 UTC, daviddavis approved these changes
ACK. I don't have merge access to this repo tho.

2016-09-20 15:49 UTC, merged

2016-09-20 15:49 UTC, stbenjam commented
Thanks @daviddavis, @chris1984