Fixes #18270 - Restart puppet services after hostname change
Katello/katello-packaging pull request #400
Opened 2017-03-23 16:24 UTC by johnpmitsch

2017-03-24 19:14 UTC, johnpmitsch commented
@akofink 

TO test:
- Spin up a 3.3 box
- Run this:
```
yum install -y git
cd ~
git clone https://github.com/Katello/katello-packaging
 git fetch upstream pull/400/head:pr400
 git checkout pr400
ln -s katello-packaging/katello/katello-change-hostname katello-change-hostname
chmod a+x katello-change-hostname 
```
- setup a product with a puppet repo and upload some puppet modules to that repo
- create a couple lifecycle envs
- create a CV and add the puppet modules
- publish and promote a CVV through the LEs
`./katello-change-hostname foo.example.com -u admin -p changeme -d`
- publish and promote a new CVV (in the same CV) through lifecycle environments

If you are able to promote a content view version with puppet modules in it after a hostname change, then bug fixed! :smile: let me know if you have any questions

2017-03-24 20:03 UTC, sean797 requested changes

2017-03-24 20:03 UTC, sean797 commented on katello/katello-change-hostname
> +`service puppetserver restart`
systemctl ? were not supporting el6 now ;) 
Also is puppetserver running on every box now? I though we run it with Passenger, at least of Puppet 3

2017-03-24 20:09 UTC, johnpmitsch commented on katello/katello-change-hostname
> +`service puppetserver restart`
@sean797 That is true, but this script is given out to use on older versions of Katello, so I used `service` to still support them.

I'm unsure about that. I had to restart puppetserver on 3.3, maybe @ehelms knows more

2017-03-24 20:20 UTC, akofink commented on katello/katello-change-hostname
> +`service puppetserver restart`
@johnpmitsch you might want to use `/sbin/system ...`. I just fixed a bug with katello-backup where the system alias in EL7 doesn't work properly if you run it from a script (i.e. a cron job that runs katello-backup). It's worth considering. https://bugzilla.redhat.com/show_bug.cgi?id=1330757

2017-03-24 20:47 UTC, ehelms commented
Looks good pending @akofink comment

2017-03-27 12:42 UTC, akofink commented
@johnpmitsch 

I'm not sure if these errors are acceptable or not. I used the centos7-katello-3.3 box on forklift:

While running `katello-change-hostname`:

```
Regenerating ueber certs
rake aborted!
Don't know how to build task 'katello:regenerate_ueber_certs'
```

Content view publishing worked fine, but promoting that version to the next lifecycle environment, I got:

```
ERF12-4115 [ProxyAPI::ProxyException]: Unable to get classes from Puppet for KT_Default_Organization_dev_cv1_2 ([RestClient::NotAcceptable]: 406 Not Acceptable) for proxy https://foo.example.com:9090/puppet
```

Here's the task export: [task-export-1490618355.tar.gz](https://github.com/Katello/katello-packaging/files/872459/task-export-1490618355.tar.gz)

2017-03-27 12:52 UTC, johnpmitsch commented
@akofink I forgot to mention that you have to comment out [this line](https://git.io/vSttM) as that rake task is not in 3.3 (an alternative is to pull in  the rake task as a patch https://github.com/Katello/katello/commit/b0a41ac9bc0c2a5ae780d8d544a33f3cb68e5300)

After you do that, you can re-run katello-change-hostname and try the CV promotion again. Sorry for the confusion

2017-03-27 13:01 UTC, johnpmitsch commented
@akofink updated to use `/sbin/service`

2017-03-27 13:53 UTC, ehelms commented
Looks good to me, will let @akofink double check

2017-03-27 14:00 UTC, akofink commented
After commenting out the line mentioned above, publish and promotion works as expected after the katello-change-hostname. ACK!

2017-03-27 15:23 UTC, ehelms commented
Thanks @johnpmitsch !

2017-03-27 15:23 UTC, merged