fixes #18328 - adds flag to confirm before shutting down services
Katello/katello-packaging pull request #459
Opened 2017-06-01 15:16 UTC by cfouant

2017-06-05 12:48 UTC, johnpmitsch requested changes

2017-06-05 12:48 UTC, johnpmitsch commented on katello/katello-backup
> +end
Highline has a simple [agree method](http://www.rubydoc.info/gems/highline/1.6.21/HighLine:agree) that could simplify this check

you can run do something like this
```
require 'highline' (at top)
response = HighLine.agree('WARNING: This script will stop your services. Do you want to proceed(y/n)?')
```

2017-06-05 12:50 UTC, johnpmitsch commented
Should we make it default to confirm the stopping of services? There could be a `-y/--yes` flag to override. I'm not sure which tactic would be better for users.

2017-06-07 20:55 UTC, cfouant commented
@johnpmitsch that would likely break a lot of cron jobs, so we are going this route instead

2017-06-07 21:06 UTC, johnpmitsch commented
@cfouant  I am thinking we should go the route of shutting down the services by default and then the user can override with `-y` for scripting. 
From the issue:
> This can have serious consequences if the user does not know ahead of time that the server will be shut down during the backup.
if the user doesn't know that services are going to be shut down, will they really pass a` --confirm-shutdown` flag? To me, it seems like to address the original intent of this issue and user frustration we should default to a confirmation and have a flag to override (similar to a command like `yum install`)

2017-06-07 21:21 UTC, cfouant commented on katello/katello-backup
> +end
Nice! Updated. Also... probably should have something for the true case scenario, guess that would help haha

2017-06-13 19:52 UTC, cfouant commented
@johnpmitsch I agree, it seems counterintuitive to add this flag, but as @ehelms pointed out, doing so would break existing cron scripts. @ehelms - your thoughts?

2017-06-27 14:55 UTC, cfouant commented
@johnpmitsch please re-review, PR has been updated to by default get user input before shutting down services.

2017-07-05 13:56 UTC, johnpmitsch approved these changes

2017-07-05 13:56 UTC, johnpmitsch commented
@cfouant approved, you need a rebase and then it's good to go :)

2017-07-10 19:52 UTC, cfouant commented
@johnpmitsch updated!

2017-07-10 19:58 UTC, merged