Move non-gofer files to katello-host-tools
Katello/katello-packaging pull request #476
Opened 2017-06-27 17:07 UTC by jlsherrill

2017-06-27 17:16 UTC, sean797 requested changes

2017-06-27 17:16 UTC, sean797 commented on katello-agent/katello-agent.spec
> +A set of commands and yum plugins that support a katello host including faster package profile uploading and bound repository reporting.  This is required for prrata and package applicability reporti
s/prrata/errata/

2017-06-27 17:21 UTC, ehelms commented on katello-agent/katello-agent.spec
> +Summary: A set of commands and yum plugins that support a katello host
Nitpick: Capital Katello

2017-06-27 17:22 UTC, ehelms commented on katello-agent/katello-agent.spec
> +Requires: %{name}-fact-plugin
Will this result in `katello-agent-fact-plugin` or the subpackage name being used? `katello-host-tools-fact-plugin` ?

2017-06-27 17:23 UTC, ehelms commented on katello-agent/katello-agent.spec
> +Group:   Development/Languages
Mind aligning with the other two fields?

2017-06-27 17:24 UTC, ehelms commented on katello-agent/katello-agent.spec
> +Requires: subscription-manager
Does this upper level package actually require subscription-manager or just the fact-plugin?

2017-06-27 19:31 UTC, jlsherrill commented on katello-agent/katello-agent.spec
> +Requires: %{name}-fact-plugin
yes, let me obsolete the old one

2017-06-27 19:31 UTC, jlsherrill commented on katello-agent/katello-agent.spec
> +Requires: subscription-manager
yes, all 3 do as they all call into subman in different ways.

2017-06-27 19:34 UTC, jlsherrill commented
Updated to move katello-host-tools as the base package, and katello-agent as the sub-package

2017-06-28 08:38 UTC, sean797 commented
Thanks @jlsherrill! 2 questions...
If I am reading this right if a users wants goferd clients you would do the usual `yum install katello-agent` and if they want gofer-less clients you would do `yum install katello-host-tools` ?

Do you think its worth renaming the katello-agent repo to katello-host-tools ?

2017-06-28 13:27 UTC, jlsherrill commented
@sean797 exactly!  I do think its worth renaming the katello-agent git repo.  I was just waiting till after this went in to do it.   I'll send an email to foreman-dev to alert everyone of the pending change and proceed after a couple days.

2017-06-28 19:34 UTC, ehelms commented
We should ensure that a package upload and an enabled repository upload occur when the `katello-host-tools` package is installed.

2017-06-28 22:28 UTC, ehelms commented
I'd like to merge this once https://github.com/theforeman/forklift/pull/478 has been approved to ensure we have testing in place.

2017-06-29 13:14 UTC, sean797 commented on katello-host-tools/katello-host-tools.spec
>  URL:     https://github.com/Katello/katello-agent
Do you want to update this now or in another PR after?

2017-06-29 13:15 UTC, sean797 approved these changes
ACK from me, thanks @jlsherrill, nice feature 👍

2017-06-29 13:18 UTC, jlsherrill commented on katello-host-tools/katello-host-tools.spec
>  URL:     https://github.com/Katello/katello-agent
If this gets merged in the next ~24 hours, i'll do a followup pr.  Otherwise I'll update before merging.

2017-06-29 13:35 UTC, ehelms approved these changes

2017-06-29 13:35 UTC, ehelms commented
@jlsherrill ACK'd -- when you want to merge and do the necessary koji work feel free. Just ping me or also merge the Forklift PR.

2017-06-29 17:42 UTC, jlsherrill commented
@ehelms updated with:

```
diff --git a/katello-host-tools/katello-host-tools.spec b/katello-host-tools/katello-host-tools.spec
index f40b743..78b668c 100644
--- a/katello-host-tools/katello-host-tools.spec
+++ b/katello-host-tools/katello-host-tools.spec
@@ -133,11 +133,11 @@ touch /tmp/katello-agent-restart
 exit 0
 
 %posttrans
-katello-package-upload &> /dev/null
-
+katello-package-upload 2> /dev/null
+katello-enabled-repos-upload 2> /dev/null
 exit 0
 
-%postun
+%postun -n katello-agent
 touch /tmp/katello-agent-restart
 exit 0
 
```

2017-06-29 18:24 UTC, ehelms commented
ACK

2017-06-30 01:16 UTC, merged

2017-06-30 01:31 UTC, jlsherrill commented
@ehelms all built in koji and ready to go

2017-06-30 02:30 UTC, ehelms commented
@jlsherrill getting repoclosure errors: http://ci.theforeman.org/view/Katello%20Pipeline/job/release_repoclosure_katello_client_nightly_el7/355/console